version : 0.0.2
container-name-run : "mymicroservice"
container-name-tools : "bx-dev-mymicroservice-tools"
image-name-run : "mymicroservice"

image-name-tools : "bx-dev-java-maven-tools"
host-path-run : "target"
build-cmd-run : "mvn install -Dmaven.repo.local=/project/.m2/repository"
test-cmd : "mvn install -Dmaven.repo.local=/project/.m2/repository"
build-cmd-debug : "mvn install -Dmaven.repo.local=/project/.m2/repository"

container-path-run : "/project"
container-path-tools : "/project"

#Liberty server settings
container-port-map : "9080:9080,9443:9443"
container-port-map-debug : "7777:7777"
debug-cmd : "server debug"


dockerfile-run : "Dockerfile"
dockerfile-tools : "Dockerfile-tools"
ibm-generated-id : "c70420ee-255d-4077-82d7-54cfa04768dc"
credentials-filepath : "src/main/liberty/config/server.env, log.txt"